#!/usr/bin/env python3
"""Render README and HN SVGs from curated Markdown and cached evidence, offline."""

import argparse
from datetime import date
import json
from pathlib import Path
import re

import update_hn as hn
import update_stats as stats

ROOT = Path(__file__).resolve().parents[1]
NOTICE = "<!-- Generated by scripts/render_readme.py; edit README.source.md instead. -->\n\n"
ENTRY = re.compile(r"^\| \[([^\]]+)\]\((https?://[^\s()<>]+)\) \| (.+) \|$")


def validate_source(text):
    """Keep curated rows free of generated content and retain two columns."""
    for line in text.splitlines():
        if not line.startswith("| "):
            continue
        if any(marker in line for marker in ("<!-- STATS:", "<!-- HN:", "assets/hn/")):
            raise ValueError("README.source.md must not contain generated STATS/HN content")
        if line.startswith(("| [", "| **[")):
            match = ENTRY.fullmatch(line)
            if not match or len(re.findall(r"(?<!\\)\|", line)) != 3:
                raise ValueError("Expected a plain project link and description in two columns: " + line)
            stats.alternatives(line)
    return stats.repositories(text, require_markers=False)


def validate_snapshot(snapshot):
    if snapshot.get("schema_version") != 1:
        raise ValueError("Unsupported GitHub metrics snapshot schema")
    as_of = date.fromisoformat(snapshot["as_of"])
    if not isinstance(snapshot.get("repositories"), dict):
        raise ValueError("Expected GitHub metrics repositories mapping")
    for repo, record in snapshot["repositories"].items():
        if not re.fullmatch(r"[\w.-]+/[\w.-]+", repo) or repo != repo.lower():
            raise ValueError("Expected lowercase canonical repository path: " + repo)
        count = record.get("stargazers_count")
        if type(count) is not int or count < 0:
            raise ValueError("Expected a nonnegative integer star count for " + repo)
        date.fromisoformat(record["created_at"][:10])
        pushed = record.get("pushed_at")
        if pushed is not None:
            date.fromisoformat(pushed[:10])
        license_value = record.get("license")
        if license_value is not None and (not isinstance(license_value, dict)
                or not isinstance(license_value.get("spdx_id"), (str, type(None)))):
            raise ValueError("Invalid license for " + repo)
    return as_of


def render_text(source, snapshot, evidence):
    validate_source(source)
    as_of = validate_snapshot(snapshot)
    # Reuse the established formatters; only this generator adds their markers.
    lines = []
    for line in source.splitlines(keepends=True):
        if stats.ROW.match(line):
            end = line.rfind(" |")
            line = line[:end] + " <!-- STATS:START --><!-- STATS:END -->" + line[end:]
        lines.append(line)
    text = stats.update_text("".join(lines), snapshot["repositories"],
                             today=as_of, allow_missing=True)
    return NOTICE + hn.decorate_readme(text, evidence)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "README.md",
                        help="Output Markdown path; assets/hn is written beside it")
    parser.add_argument("--strict-metrics", action="store_true",
                        help="Fail when a listed GitHub repository has no cached metrics")
    args = parser.parse_args()
    source = (ROOT / "README.source.md").read_text(encoding="utf-8")
    snapshot = json.loads((ROOT / "data/github_metrics.json").read_text(encoding="utf-8"))
    evidence = json.loads((ROOT / "data/hn_evidence.json").read_text(encoding="utf-8"))
    repos = validate_source(source)
    missing = sorted(set(repos) - snapshot["repositories"].keys())
    if missing and args.strict_metrics:
        parser.error("Missing cached metrics: " + ", ".join(missing))
    rendered = render_text(source, snapshot, evidence)
    # Validate all SVGs and filenames before writing any output.
    for project in evidence["projects"]:
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", project["slug"]):
            raise ValueError("Invalid HN asset slug")
        if project["eligible"]:
            hn.svg(project, evidence)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    hn.render(evidence, args.output.parent / "assets/hn")
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Rendered {args.output} offline; GitHub metrics as of {snapshot['as_of']}.")
    if missing:
        print("Metrics omitted until the publisher refreshes: " + ", ".join(missing))


if __name__ == "__main__":
    main()
